package org.jeecg.modules.api.xbus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.11
 * 2019-11-20T10:20:36.293+08:00
 * Generated source version: 3.2.11
 *
 */
@WebServiceClient(name = "ISoapWebServiceService",
             /*     wsdlLocation = "file:/C:/Users/laowang/AppData/Local/Temp/tempdir4541953000469166280.tmp/soap_1.wsdl",*/
                  targetNamespace = "http://webservice.esb.sphchina.com")
public class ISoapWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.esb.sphchina.com", "ISoapWebServiceService");
    public final static QName ReceiveMessagePort = new QName("http://webservice.esb.sphchina.com", "receiveMessagePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/laowang/AppData/Local/Temp/tempdir4541953000469166280.tmp/soap_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ISoapWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/laowang/AppData/Local/Temp/tempdir4541953000469166280.tmp/soap_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ISoapWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ISoapWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISoapWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ISoapWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ISoapWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ISoapWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ReceiveMessage
     */
    @WebEndpoint(name = "receiveMessagePort")
    public ReceiveMessage getReceiveMessagePort() {
        return super.getPort(ReceiveMessagePort, ReceiveMessage.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReceiveMessage
     */
    @WebEndpoint(name = "receiveMessagePort")
    public ReceiveMessage getReceiveMessagePort(WebServiceFeature... features) {
        return super.getPort(ReceiveMessagePort, ReceiveMessage.class, features);
    }

}
