package org.jeecg.modules.api.xbus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.11
 * 2019-11-20T10:20:36.284+08:00
 * Generated source version: 3.2.11
 *
 */
@WebService(targetNamespace = "http://webservice.esb.sphchina.com", name = "receiveMessage")
@XmlSeeAlso({ObjectFactory.class})
public interface ReceiveMessage {

    @WebMethod
    @RequestWrapper(localName = "receiveMessage", targetNamespace = "http://webservice.esb.sphchina.com", className = "org.jeecg.modules.api.xbus.ReceiveMessage_Type")
    @ResponseWrapper(localName = "receiveMessageResponse", targetNamespace = "http://webservice.esb.sphchina.com", className = "org.jeecg.modules.api.xbus.ReceiveMessageResponse")
    @WebResult(name = "DefaultWebServiceResponse", targetNamespace = "http://webservice.esb.sphchina.com")
    public DefaultWebServiceResponse receiveMessage(
            @WebParam(name = "DefaultWebServiceRequest", targetNamespace = "http://webservice.esb.sphchina.com")
                   DefaultWebServiceRequest defaultWebServiceRequest
    );
}
