package com.sphchina.esb.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2019-10-30T16:35:33.645+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://webservice.esb.sphchina.com", name = "xbusServiceTestService")
@XmlSeeAlso({ObjectFactory.class})
public interface XbusServiceTestService {

    @WebMethod
    @RequestWrapper(localName = "xBusTest", targetNamespace = "http://webservice.esb.sphchina.com", className = "com.sphchina.esb.webservice.XBusTest")
    @ResponseWrapper(localName = "xBusTestResponse", targetNamespace = "http://webservice.esb.sphchina.com", className = "com.sphchina.esb.webservice.XBusTestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.sphchina.esb.webservice.DefaultWebServiceResponse xBusTest(
        @WebParam(name = "defaultWebServiceRequest", targetNamespace = "")
        com.sphchina.esb.webservice.DefaultWebServiceRequest defaultWebServiceRequest
    );
}
