package com.sphchina.esb.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2019-10-30T16:35:33.707+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "XbusServiceTestServiceImplService", 
                  wsdlLocation = "file:/C:/Users/laowang/Desktop/xbusTest.wsdl.wsdl",
                  targetNamespace = "http://webservice.esb.sphchina.com") 
public class XbusServiceTestServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.esb.sphchina.com", "XbusServiceTestServiceImplService");
    public final static QName XbusServiceTestServicePort = new QName("http://webservice.esb.sphchina.com", "xbusServiceTestServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/laowang/Desktop/xbusTest.wsdl.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(XbusServiceTestServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/laowang/Desktop/xbusTest.wsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public XbusServiceTestServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XbusServiceTestServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XbusServiceTestServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public XbusServiceTestServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public XbusServiceTestServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public XbusServiceTestServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns XbusServiceTestService
     */
    @WebEndpoint(name = "xbusServiceTestServicePort")
    public XbusServiceTestService getXbusServiceTestServicePort() {
        return super.getPort(XbusServiceTestServicePort, XbusServiceTestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XbusServiceTestService
     */
    @WebEndpoint(name = "xbusServiceTestServicePort")
    public XbusServiceTestService getXbusServiceTestServicePort(WebServiceFeature... features) {
        return super.getPort(XbusServiceTestServicePort, XbusServiceTestService.class, features);
    }

}
